appraisal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path('', include('usermanagement.urls')),
    # path('admin/', admin.site.urls),
    path('', include('configuration.urls')),
    path('kpi/', include('kpimanagement.urls')),
]

configuration/urls.py
from django.urls import path
from .views import *

app_name = 'configuration'

urlpatterns = [

    # employee
    path('epm/', EmployeeListView.as_view(), name='EmployeeListView'),
    path('add/', EmployeeCreateView.as_view(), name='EmployeeCreateView'),
    path('employeeedit/edit/<pk>/', EmployeeUpdateView.as_view(), name='EmployeeUpdateView'),
    path('employeeedit/delete/<pk>/', EmployeeDeleteView.as_view(), name='EmployeeDeleteView'),

    # kpi-configuration
    path('kpiconfig/', KPIConfigListView.as_view(), name='KPIConfigListView'),
    path('kpiconfigadd/', KPIConfigCreateView.as_view(), name='KPIConfigCreateView'),
    path('kpiconfigedit/edit/<pk>/', KPIConfigUpdateView.as_view(), name='KPIConfigUpdateView'),
    path('kpiconfigdelete/delete/<pk>/', KPIConfigDeleteView.as_view(), name='KPIConfigDeleteView'),

    # review-rating
    path('reviewrating/', ReviewRatingListView.as_view(), name='ReviewRatingListView'),
    path('reviewratingadd/', ReviewRatingCreateView.as_view(), name='ReviewRatingCreateView'),
    path('reviewratingedit/edit/<pk>/', ReviewRatingUpdateView.as_view(), name='ReviewRatingUpdateView'),
    path('reviewratingdeleteView/delete/<pk>/', ReviewRatingDeleteView.as_view(), name='ReviewRatingDeleteView'),

    # supervisor
    path('supervisor/', SupervisorListView.as_view(), name='SupervisorListView'),
    path('supervisoradd/', SupervisorCreateView.as_view(), name='SupervisorCreateView'),
    path('supervisoredit/edit/<pk>/', SupervisorUpdateView.as_view(), name='SupervisorUpdateView'),
    path('supervisoredelete/delete/<pk>/', SupervisorDeleteView.as_view(), name='SupervisorDeleteView'),

    # project
    path('project/', ProjectListView.as_view(), name='ProjectListView'),
    path('projectadd/', ProjectCreateView.as_view(), name='ProjectCreateView'),
    path('projectedit/edit/<pk>/', ProjectUpdateView.as_view(), name='ProjectUpdateView'),
    path('projectdelete/delete/<pk>/', ProjectDeleteView.as_view(), name='ProjectDeleteView'),

    # sbu
    path('sbu/', SBUListView.as_view(), name='SBUListView'),
    path('sbuadd/', SBUCreateView.as_view(), name='SBUCreateView'),
    path('sbuedit/edit/<pk>/', SBUUpdateView.as_view(), name='SBUUpdateView'),
    path('sbudelete/delete/<pk>/', SBUDeleteView.as_view(), name='SBUDeleteView'),

    # sub-sbu
    path('subsbu/', SubSBUListView.as_view(), name='SubSBUListView'),
    path('subsbuadd/', SubSBUCreateView.as_view(), name='SubSBUCreateView'),
    path('subsbuedit/edit/<pk>/', SubSBUUpdateView.as_view(), name='SubSBUUpdateView'),
    path('subsbudelete/delete/<pk>/', SubSBUDeleteView.as_view(), name='SubSBUDeleteView'),

    # kpi-objective
    path('kpiobjective/', KPIObjectiveListView.as_view(), name='KPIObjectiveListView'),
    path('kpiobjectivebuadd/', KPIObjectiveCreateView.as_view(), name='KPIObjectiveCreateView'),
    path('kpiobjectiveedit/edit/<pk>/', KPIObjectiveUpdateView.as_view(), name='KPIObjectiveUpdateView'),
    path('kpiobjectivedelete/delete/<pk>/', KPIObjectiveDeleteView.as_view(), name='KPIObjectiveDeleteView'),
]

configuration/views.py
from datetime import datetime
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
import requests
from configuration.forms import EmployeeForm, KPIConfigForm, ReviewRatingForm, SupervisorForm, ProjectForm, SBUForm, SubSBUForm, KPIObjectiveForm
from configuration.models import *
from django.utils.decorators import method_decorator
from usermanagement.decorators import login_required, access_permission_required
# Create your views here.
# @method_decorator(login_required("logged_in", 'usermanagement:login'), name='dispatch')
# @method_decorator(access_permission_required, name='dispatch')


class EmployeeListView(ListView):
    model = Employee
    template_name = 'configuration/employee/employee_list.html'
    context_object_name = 'employee'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(EmployeeListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['employee'] = self.model.objects.all()
        return context

class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'configuration/employee/employee_add.html'
    success_url = reverse_lazy('configuration:EmployeeListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(EmployeeCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        print(form)
        if form.is_valid:
            employee = form.save(commit=False)
            employee.created_date = datetime.now()
            employee.updated_date = datetime.now()
            employee.created_by_id =self.request.session['id']
            employee.updated_by_id =self.request.session['id']
            employee.save()
            messages.success(self.request, 'Data Successfully Saved')
            return super(EmployeeCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(EmployeeCreateView, self).form_invalid(form)

class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'configuration/employee/employee_update.html'
    success_url = reverse_lazy('configuration:EmployeeListView')
    context_object_name = 'employeeedit'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(EmployeeUpdateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        # context['form'] = self.form_class
        return context

    def form_valid(self, form):

        if form.is_valid:
            employee = form.save(commit=False)
            employee.updated_by_id =self.request.session['id']
            employee.updated_date = datetime.now()
            employee.save()
            messages.success(self.request, 'Data Successfully Updated')
            return super(EmployeeUpdateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(EmployeeUpdateView, self).form_invalid(form)

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'configuration/employee/employee_delete.html'
    success_url = reverse_lazy('configuration:EmployeeListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(EmployeeDeleteView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context

    def get_success_url(self):
        messages.success(self.request, 'Data Successfully Deleted')
        return reverse_lazy('configuration:EmployeeListView')



class KPIConfigListView(ListView):
    model = KPIConfig
    template_name = 'configuration/kpiconfiguration/kpiconfiguration_list.html'
    context_object_name = 'kpiconfigs'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(KPIConfigListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['employee'] = self.model.objects.all()
        return context

class KPIConfigCreateView(CreateView):
    model = KPIConfig
    form_class = KPIConfigForm
    template_name = 'configuration/kpiconfiguration/kpiconfiguration_add.html'
    success_url = reverse_lazy('configuration:KPIConfigListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(KPIConfigCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        print(form)
        if form.is_valid:
            kpiconfig = form.save(commit=False)
            kpiconfig.created_date = datetime.now()
            kpiconfig.updated_date = datetime.now()
            kpiconfig.created_by_id =self.request.session['id']
            kpiconfig.updated_by_id =self.request.session['id']
            kpiconfig.save()
            messages.success(self.request, 'Data Successfully Saved')
            return super(KPIConfigCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(KPIConfigCreateView, self).form_invalid(form)

class KPIConfigUpdateView(UpdateView):
    model = KPIConfig
    form_class = KPIConfigForm
    template_name = 'configuration/kpiconfiguration/kpiconfiguration_update.html'
    success_url = reverse_lazy('configuration:KPIConfigListView')
    context_object_name = 'kpiconfigedit'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(KPIConfigUpdateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        # context['form'] = self.form_class
        return context

    def form_valid(self, form):

        if form.is_valid:
            kpiconfig = form.save(commit=False)
            kpiconfig.updated_by_id =self.request.session['id']
            kpiconfig.updated_date = datetime.now()
            kpiconfig.save()
            messages.success(self.request, 'Data Successfully Updated')
            return super(KPIConfigUpdateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(KPIConfigUpdateView, self).form_invalid(form)

class KPIConfigDeleteView(DeleteView):
    model = KPIConfig
    template_name = 'configuration/kpiconfiguration/kpiconfiguration_delete.html'
    success_url = reverse_lazy('configuration:KPIConfigListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(KPIConfigDeleteView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context

    def get_success_url(self):
        messages.success(self.request, 'Data Successfully Deleted')
        return reverse_lazy('configuration:KPIConfigListView')



class ReviewRatingListView(ListView):
    model = ReviewRating
    template_name = 'configuration/reviewrating/reviewrating_list.html'
    context_object_name = 'reviewratings'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(ReviewRatingListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['employee'] = self.model.objects.all()
        return context

class ReviewRatingCreateView(CreateView):
    model = ReviewRating
    form_class = ReviewRatingForm
    template_name = 'configuration/reviewrating/reviewrating_add.html'
    success_url = reverse_lazy('configuration:ReviewRatingListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'urls': self.request.session['urls'],
        }
        context = super(ReviewRatingCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        print(form)
        if form.is_valid:
            reviewrating = form.save(commit=False)
            reviewrating.created_date = datetime.now()
            reviewrating.updated_date = datetime.now()
            reviewrating.created_by_id =self.request.session['id']

templates/configuration/sbu/sbu_add.html
{% extends 'main.html' %}
{% load static %}
{#{% load countries %}#}
{% block content %}
    <!-- Content wrapper -->
    <div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">
        {#        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light"></span> Add Employee#}
        {#        </h4>#}
        {% for msg in messages %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-xxl">
                  <div class="card mb-4">
                    <div class="card-header d-flex align-items-center justify-content-between">
                      <h5 class="mb-0">Basic Layout</h5>
                      <small class="text-muted float-end">Default label</small>
                    </div>
                    <div class="card-body">
                     <form  action=" " method="post" enctype="multipart/form-data"
                                  id="validate-form" autocomplete="off">
                      {% csrf_token %}
                        <div class="row mb-3">
                            {% for field in form %}

                                        <label for="{{ field.id_for_label }} " class="col-sm-2 col-form-label" for="basic-default-name">
                                            {% if field.field.required %}
                                                <span class="required">{{ field.label }}*</span>
                                            {% else %}
                                                {{ field.label }}
                                            {% endif %}
                                        </label>
                                <div class="col-sm-10">{{ field }}</div>

                                {% endfor %}

                          </div>

                        <div class="row justify-content-end">
                          <div class="col-sm-10">
                           <button type="submit" class="btn btn-primary me-3 ">Save changes</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
        </div>
    </div>
    <!-- / Content -->
{% endblock %}

templates/configuration/sbu/sbu_delete.html
{% extends 'main.html' %}
{% load static %}
{#{% load countries %}#}
{% block content %}
    <!-- Content wrapper -->
    <div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">
        {#        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light"></span> Add Employee#}
        {#        </h4>#}
        {% for msg in messages %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <h5 class="card-header">Sbu Delete</h5>
                    <hr class="my-0"/>
                    <div class="card-body">
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <span style="font-size: x-large">CAUTION!</span>
                            <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="row">
                                <p><h6><b>DO YOU WANT TO DELETE THE FOLLOWING Sbu?</b></h6></p>
                                <p><b> Name :</b> {{ object.name }}</p>


                            </div>
                            <div class="mt-4">
                                <button type="submit" class="btn btn-primary me-3 ">Delete</button>
                                <a href="{% url "configuration:SBUListView" %}">
                                    <button type="button" class="btn btn-outline-secondary">Cancel</button>
                                </a>
                            </div>
                        </form>
                    </div>
                    <!-- /Account -->
                </div>
            </div>
        </div>
    </div>
    <!-- / Content -->
{% endblock %}

templates/configuration/sbu/sbu_list.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    <!-- Content wrapper -->
    <div class="content-wrapper">
        <!-- Content -->
        <div class="container-xxl flex-grow-1 container-p-y">
            <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light"></span> SBU <span
                    style="float: right"><a href="{% url 'configuration:SBUCreateView' %}"
                                            class="btn btn-secondary" role="button">Add SBU</a></span>
            </h4>
            {% for msg in messages %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    {{ msg }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            <!-- Responsive Table -->
            <div class="card">
                <h5 class="card-header">SBU</h5>
                <div class="table-responsive text-nowrap">
                    <table class="table">
                        <thead>
                        <tr class="text-nowrap">
                            {#                            <th>#</th>#}
                            <th>Name</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for data in sbus %}
                            <tr>
                                <th scope="row">{{ data.name }} </th>
                                <td>

                                    <a href="{% url 'configuration:SBUUpdateView' data.id %}">
                                        <button class="btn btn-success btn-sm rounded" type="button"
                                                data-toggle="tooltip"
                                                data-placement="top" title="Edit">Edit
                                        </button>
                                    </a>
                                    &nbsp
                                    <a href="{% url 'configuration:SBUDeleteView' data.id %}">
                                        <button class="btn btn-danger btn-sm rounded" type="button"
                                                data-toggle="tooltip"
                                                data-placement="top" title="Delete">Delete
                                        </button>
                                    </a>
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!--/ Responsive Table -->
        </div>
        <!-- / Content -->
{% endblock %}

templates/configuration/sbu/sbu_update.html
{% extends 'main.html' %}
{% load static %}
{#{% load countries %}#}
{% block content %}
    <!-- Content wrapper -->
    <div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">
        {#        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light"></span> Add Employee#}
        {#        </h4>#}
        {% for msg in messages %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <h5 class="card-header">SBU Update</h5>
                    <hr class="my-0"/>
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}

                            <div class="row">

                                 {{ form.as_p }}

                            </div>
                            <div class="mt-4">
                                <button type="submit" class="btn btn-primary me-3 ">Save changes</button>
                                <a href="">
                                    <button type="button" class="btn btn-outline-secondary">Cancel</button>
                                </a>
                            </div>
                        </form>
                    </div>
                    <!-- /Account -->
                </div>
            </div>
        </div>
    </div>
    <!-- / Content -->
{% endblock %}